media:
  input: src/assets/images
content:
  - name: businesses
    label: Businesses
    type: collection
    path: src/content/businesses
    filename: "{id}.mdx"
    fields:
      - name: name
        label: Name
        type: string
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: code
        options:
          language: markdown

