media:
  input: src/assets/images
content:
  - name: businesses
    label: Businesses
    type: collection
    path: src/content/businesses
    filename: '{id}.mdx'
    fields:
      - name: id
        label: Id
        type: string
        

